services:
  api:
    build: .
    env_file: .env
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      MONGODB_URI: mongodb://mongo:27017/nest_api
      REDIS_URL: redis://redis:6379
      MAIL_HOST: ${MAIL_HOST:-mailpit}

  mongo:
    image: mongo:8
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit:v1.27
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mongo_data:
  redis_data:
